texto = input('Digite algo a ser avaliado pelos métodos de string: ')

print('É alfanumérico? ', texto.isalnum())
print('É alfabético? ', texto.isalpha())
print('É ASCII? ', texto.isascii())
print('É decimal? ', texto.isdecimal())
print('É dígito? ', texto.isdigit())
print('É numérico? ', texto.isnumeric())
print('É identificador? ', texto.isidentifier())
print('É minúscula? ', texto.islower())
print('É maiúscula? ', texto.isupper())
print('É título? ', texto.istitle())
print('É espaço? ', texto.isspace())
print('É imprimível? ', texto.isprintable())